apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-external-networks
spec:
  description: Fetches external network definitions from StackRox artifacts to be baked into the image.
  params:
  - name: TARGET_DIR
    description: Target directory relative to workspace where to save downloaded files.
    type: string
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the application source code.
    type: string
  - name: ociStorage
    description: The OCI repository where the Trusted Artifacts are stored.
    type: string
  - name: ociArtifactExpiresAfter
    description: Expiration date for the trusted artifacts created in the
      OCI repository.
    type: string
  results:
  - name: SOURCE_ARTIFACT
    description: The Trusted Artifact URI pointing to the artifact with the application source code
      and additional external network definitions.
    type: string
  volumes:
  - name: workdir
    emptyDir: { }
  stepTemplate:
    volumeMounts:
    - mountPath: /var/workdir
      name: workdir
  steps:
  - name: use-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
    args:
    - use
    - $(params.SOURCE_ARTIFACT)=/var/workdir/source
  - name: fetch-external-networks
    image: registry.access.redhat.com/ubi9-minimal:latest@sha256:dee813b83663d420eb108983a1c94c614ff5d3fcb5159a7bd0324f0edbe7fca1
    workingDir: /var/workdir/source
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      microdnf -y install zip
      image/rhel/fetch-stackrox-data.sh "$(params.TARGET_DIR)"
  - name: create-trusted-artifact
    image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:81c4864dae6bb11595f657be887e205262e70086a05ed16ada827fd6391926ac
    args:
    - create
    - --store
    - $(params.ociStorage)
    - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
    env:
    - name: IMAGE_EXPIRES_AFTER
      value: $(params.ociArtifactExpiresAfter)
